services:
  nodered:
    build: .
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./data-node-red:/data
    restart: always
    # O command é definido no entrypoint.sh → não precisa aqui